version: "3.7"
services:
  php:
    build:
      args:
        user: yusif
        uid: 1000
      context: ./php
      dockerfile: Dockerfile
    image: myapp
    container_name: app_php
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./../:/var/www
    networks:
      - app_network

  nginx:
    image: nginx:alpine
    container_name: app_nginx
    restart: unless-stopped
    ports:
      - 8086:80
    volumes:
      - ./../:/var/www
      - ./nginx:/etc/nginx/conf.d/
    networks:
      - app_network

  mysqldb:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    image: mysql
    platform: linux/amd64
    container_name: mysql_container
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - "../.env"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=mydataa
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=password
    ports:
      - "3316:3306"
    volumes:
      - "./data/db/mysql:/var/lib/mysql"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
