INSERT INTO `currencies` (`id`, `code`, `name`, `symbol`) VALUES
(1, 'ALL', 'Leke', 'Lek'),
(2, 'USD', 'Dollars', '$'),
(7, 'AZN', 'New Manats', 'ман'),
(10, 'BYR', 'Rubles', 'p.'),
(11, 'EUR', 'Euro', '€'),
(19, 'GBP', 'Pounds', '£'),
(25, 'CNY', 'Yuan Renminbi', '¥'),
(53, 'JPY', 'Yen', '¥'),
(55, 'KZT', 'Tenge', 'лв'),
(87, 'RUB', 'Rubles', 'руб'),
(89, 'SAR', 'Riyals', '﷼'),
(90, 'RSD', 'Dinars', 'Дин.'),
(108, 'UZS', 'Sums', 'лв'),
(111, 'YER', 'Rials', '﷼'),
(113, 'INR', 'Rupees', '₹');
